apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./infra/k8s/*.yaml
build:
    local:
        push: false
    artifacts:
        - image: refaey99/ticketing-auth
          context: auth
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        - image: refaey99/ticketing-client
          context: client
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: '**/*.js'
                    dest: .
        - image: refaey99/ticketing-tickets
          context: tickets
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        - image: refaey99/ticketing-orders
          context: orders
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        - image: refaey99/ticketing-expiration
          context: expiration
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        - image: refaey99/ticketing-payments
          context: payments
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
