name: tests-orders

# When we are running this workflow
on:
    pull_request:
        paths:
            - 'orders/**'

# Define what we want to do whenever a pull request is created/updated
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd orders && npm install && npm run test:ci
